[BrokenLinksH2] Fix path in link
MicrosoftDocs/WSL pull request #1542
Opened 2022-06-06 23:43 UTC by DhurataJ

Broken links related to "LTP Test Run Logs" are removed since no longer exist in GitHub repo.

2022-06-06 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[6ebf46c](https://github.com/DhurataJ/WSL/commits/6ebf46c9b3dcf512f33d2e80ed5813babf3843a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WSL/release-notes.md](https://github.com/MicrosoftDocs/WSL/blob/main/WSL/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/wsl/release-notes?branch=pr-en-us-1542) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/679c7023-7559-8831-3c77-6434edf8d58b/202206062343324992-1542/BuildReport?accessString=8b29c0f04cc41f283f65baa0e79fcaa56830f6349ccf23beaf9120f97388c1a4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/679c7023-7559-8831-3c77-6434edf8d58b?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 23:47 UTC, DhurataJ commented
**Global effort to fix broken links**

@craigloewen-msft 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. In this particular PR I removed broken links, since the target no longer exist in repo. I'd very much appreciate your timely review and feedback on the link changes I've suggested. Thanks!

2022-06-24 17:14 UTC, pmartincic commented on WSL/release-notes.md
> +  - More information on handling these files in Windows can be found [here](/windows/wsl/case-sensitivity).
Can you update this link? I think they must have moved it since you wrote this.

2022-06-24 18:42 UTC, pmartincic requested changes
If the last link gets updated to point to the new md file I'll merge it.

Thanks!

2022-06-24 19:02 UTC, opbld30 commented
Docs Build status updates of commit _[b9767cd](https://github.com/DhurataJ/WSL/commits/b9767cda0511a77146c3b9b8c7255c52fdcca8e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WSL/release-notes.md](https://github.com/DhurataJ/WSL/blob/patch-1/WSL/release-notes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/windows/wsl/release-notes?branch=pr-en-us-1542) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/679c7023-7559-8831-3c77-6434edf8d58b/202206241901476934-1542/BuildReport?accessString=74911305513044d88482822386da2c3720cbd8ded258d4c97b4728af3081a81d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/679c7023-7559-8831-3c77-6434edf8d58b?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-24 19:14 UTC, merged