User/chdhan/wsl troubleshooting doc update 3 18 23
MicrosoftDocs/WSL pull request #1936
Opened 2024-03-19 02:57 UTC by chanpreetdhanjal

Updated below - 

In [Advanced settings configuration in WSL | Microsoft Learn](https://learn.microsoft.com/en-us/windows/wsl/wsl-config), in the section about "hostAddressLoopback" -> add a note to mention "only IPv4 addresses assigned to the host are supported"

In [Advanced settings configuration in WSL | Microsoft Learn](https://learn.microsoft.com/en-us/windows/wsl/wsl-config), in the section about "localhostForwarding" -> add a note to mention "setting is ignored when networkingMode=mirrored"

In [Accessing network applications with WSL | Microsoft Learn](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking), update phrase below to also include "IPv6 localhost address ::1 is not supported"
"Connect to Windows servers from within Linux using the localhost address 127.0.0.1"

2024-03-19 15:57 UTC, craigloewen-msft approved these changes

2024-03-19 16:56 UTC, keith-horton approved these changes

2024-03-20 06:43 UTC, keith-horton requested changes
I don't think this statement is correct: "Also only IPv4 addresses assigned to the host are supported." under hostAddressLoopback.

I thought we tested this. I'll need to get back to you.

2024-03-20 17:03 UTC, keith-horton approved these changes
Confirmed: the updated text is 100% accurate.

2024-03-20 18:06 UTC, mattwojo approved these changes

2024-03-20 18:55 UTC, merged