Resolution to problem with Linux $PATH variable not being populated correctly in some distributions
MicrosoftDocs/WSL pull request #880
Opened 2020-08-31 00:38 UTC by dimithras

Added a short walk-through to eliminate the problem with Linux $PATH variable not being populated by wsl.
This article features running `explorer.exe . ` inside distribution Linux Terminal but fails of some distros.

Closes #878

Resolves microsoft/WSL#5779
Resolves microsoft/WSL#5296
Closed microsoft/WSL#4243

2020-08-31 00:38 UTC, opbld30 commented
Docs Build status updates of commit _[af8a5ad](https://github.com/dimithras/WSL/commits/af8a5ad31e21b9280da0330a41b7904e2998a516)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[WSL/compare-versions.md](https://github.com/dimithras/WSL/blob/patch-1/WSL/compare-versions.md) | :bulb:Suggestion | | [Details](#user-content-6d7b9b72-352b5221)

<a id="6d7b9b72-352b5221"></a>
### [WSL/compare-versions.md](https://github.com/dimithras/WSL/blob/patch-1/WSL/compare-versions.md)
 - **Line 119, Column 1**: **[Suggestion-image-alt-text-duplicated]** `````Alt text 'Accessing Linux network applications from Windows' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````
 - **Line 130, Column 1**: **[Suggestion-image-alt-text-duplicated]** `````Alt text 'Accessing Linux network applications from Windows' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning in late October, 2020.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C31%5C679c7023-7559-8831-3c77-6434edf8d58b%5CPullRequest%5C202008310038129498-880%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AuJ2pShY2PejqfhWFQswlks2xQCVxye0n449KATFjgY%3D&st=2020-08-31T00%3A33%3A51Z&se=2020-10-01T00%3A38%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/679c7023-7559-8831-3c77-6434edf8d58b?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-19 00:03 UTC, mattwojo commented
Looks good to me. @craigloewen-msft could you take a look and approve / merge? 

Thanks for contributing @dimithras!!! Very appreciated!!!

2020-09-19 00:05 UTC, mattwojo approved these changes

2020-09-22 18:45 UTC, dimithras commented
Many thanks @mattwojo for initial review of this PR and @craigloewen-msft for approving previous one.

#### Would you mind if I ask to assist on improving a localized version?  
As far as I see it has an automatized bot maintainer at the moment.
I've created a PR (https://github.com/MicrosoftDocs/WSL.ru-RU/pull/10) with edits and I'm concerned it's not going to be reviewed. While most of edits are minor, there is [a key article](https://github.com/MicrosoftDocs/WSL.ru-RU/pull/10/commits/7c25c2df596fdf21805b5c8578b87849f1f7870c) that features **MT** (machine translated). If needed, I can adjust PR to include only this one. Comments are written in English.  
There are several other small MT articles of less significance, will be happy to translate those also.

2020-09-28 16:29 UTC, craigloewen-msft commented on WSL/compare-versions.md
> +### Accsess the Linux file system and run Windows commands inside distribution
```suggestion
### Access the Linux file system and run Windows commands inside distribution
```

2020-09-28 16:29 UTC, craigloewen-msft commented on WSL/compare-versions.md
> +All currently running distributions (`wsl -l`) are accessible via network connection. To get there run a coomand \[WIN+R\] keyboard shortcut or type in File Explorer adress bar `\\wsl$` to find respe
```suggestion
All currently running distributions (`wsl -l`) are accessible via network connection. To get there run a command \[WIN+R\] keyboard shortcut or type in File Explorer address bar `\\wsl$` to find respective ditto names and access their root file systems.
```

2020-09-28 16:31 UTC, craigloewen-msft commented on WSL/compare-versions.md
> +You can also use windows commands inside wsl Linux [Terminal](https://en.wikipedia.org/wiki/Linux_console). Try opening a Linux distribution (ie Ubuntu), be sure that you are in the Linux home direct
```suggestion
You can also use windows commands inside WSL's Linux [Terminal](https://en.wikipedia.org/wiki/Linux_console). Try opening a Linux distribution (ie Ubuntu), be sure that you are in the Linux home directory by entering this command: `cd ~`. Then open your Linux file system in File Explorer by entering *(don't forget the period at the end)*: `powershell.exe /c start .`
```

2020-09-28 16:32 UTC, craigloewen-msft commented
Overall this content is helpful, but I don't think that `compare-versions.md` is the right place to put it. Nothing in this paragraph compares WSL 1 and WSL 2, and all commands can be used interchangeably between the two distro versions. I think putting this content in this file could cause confusion for users.

2020-09-28 16:33 UTC, craigloewen-msft requested changes

2020-09-28 16:33 UTC, craigloewen-msft commented on WSL/compare-versions.md
> +### Accsess the Linux file system and run Windows commands inside distribution
Blocking this based on the suggested changes and the fact that this content is in the `compare-versions.md` doc but doesn't compare the WSL versions.

2020-09-28 18:37 UTC, dimithras commented
@craigloewen-msft thanks for provided review and apologies for typos.  
Completely agree, this might be misleading.    

Yet, when I followed the guide in **compare-versions.md** and tried out `explorer.exe .` in Debian (as my first distro), found myself confused as the command did not work.

I guess the best approach would be to place this content in **troubleshooting.md** and provide a reference to it in **compare-versions.md**.

Will prepare a separate PR as I accidentally deleted the branch and can not do any changes further.

2020-09-28 18:37 UTC, closed without merging